### ISSUE TITLE
$myProject/myModule : yo yui3:addtemplate

### ISSUE THREAD

**Issue by BenNG** [charlypoly/generator-yui3#3]
par defaut "yo yui3:addtemplate" créer un fichier myModuleName.handlebars.html dans le dossier myModuleName/templates.

"yo yui3:addtemplate qqchose" créer un fichier myModuleName-qqchose.handlebars.html dans le dossier myModuleName/templates.

**Comment by BenNG** [comment]
Comment le myModule/build.json doit etre mis à jour maintenant ?
(  "../templates/view-login-emailNotFound.js"    "../../../../../../script/yui3_template_compiler.js" etc)

**Comment by BenNG** [comment]
Sortir pushOnce() pour l'utiliser partout ?

**Comment by charlypoly** [comment]
@BenNG pour le build, il faut rajouter "yo yui3:handlebars" ;)

Je vais faire une fichier common.js avec des fonctions utiles partout du coup

**Comment by BenNG** [comment]
f1e59630e458c740fb622daae11bb03c1dbf9b41
055904499c5261b75df91d4b7832fb95ac4a6f30
d98cc4c72ec5e1e0e633fc5a30dfcb7cf331d47a
4f3452050af0e6003d191563f8379807727b13e8
