### ISSUE TITLE
$myProject/myModule : yo yui3:addlang

### ISSUE THREAD

**Issue by charlypoly** [charlypoly/generator-yui3#5]
### Add lang to current module

this command will update meta file and add files into `lang/` folder

Example : 

```
$myProject/myModule> yo yui3:addlang de,en,es
$myProject/myModule> "module updated !"
```

**Comment by BenNG** [comment]
dans le fichier .generator-yui3.json, je pense qu'il vaut mieux créer une section lang plutôt que de l'écrire à chaque  dans fois dans modules/base, modules/widget ...

**Comment by BenNG** [comment]
Mais ça risque de tout pt

**Comment by BenNG** [comment]
1c1ef055a34b859638fb85c9b361d31bf59159ac
